export const SAVE_PERSONS_TO_STORE='SAVE_PERSONS_TO_STORE';
export const LOADING_START='LOADING_START';
export const LOADING_END='LOADING_END';
export const OPEN_MODAL='OPEN_MODAL';
export const CLOSE_MODAL='CLOSE_MODAL';
export const SEND_PERSON_DETAIL='SEND_PERSON_DETAIL';
export const ADD_VIEW_COUNT='ADD_VIEW_COUNT';
